<?php
$categories = $this->getStoreCategories(true,false,true);
$categoryHelper = $this->getCategoryHelper();
?>
<h3><?php echo __('Categories'); ?></h3>
<div class="filter-options-content">

<?php
foreach($categories as $category):
     if (!$category->getIsActive()) {
        continue;
     }

?>
<ol class="items">
<li class="item"><a href="<?php echo $categoryHelper->getCategoryUrl($category) ?>"><?php echo $category->getName() ?></a></li>
<?php  
if($childrenCategories = $this->getChildCategories($category)):
?>
<ol class="child-categories">
<?php
foreach($childrenCategories as $childrenCategory):
     if (!$childrenCategory->getIsActive()) {
        continue;
     }
?>
<li><a href="<?php echo $categoryHelper->getCategoryUrl($childrenCategory) ?>"><?php echo $childrenCategory->getName() ?></a></li>
<?php
endforeach;
?>
</ol>
</ol>
<?php
endif;
endforeach;
?>
</div>

